easy_admin:
    resource: '@EasyAdminBundle/Controller/'
    type: annotation
    prefix: /admin
    entities:
        - App\Entity\User
        - App\Entity\Service
        - App\Entity\Habitat
        - App\Entity\Metier
        - App\Entity\Horaire
        - App\Entity\Animal
        - App\Entity\Race
        - App\Entity\Nourriture
        - App\Entity\TypeNourriture
        - App\Entity\RapportVeto
    dashboard:
        title: 'Admin Dashboard'
    menu:
        - { label: 'Dashboard', route: 'admin_dashboard' }
   