vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        animal_images:
            uri_prefix: /images/animal
            upload_destination: '%kernel.project_dir%/public/images/animal'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        habitat_images:
            uri_prefix: /images/habitat
            upload_destination: '%kernel.project_dir%/public/images/habitat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
