vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        animal_images:
            uri_prefix: /images/animal
            upload_destination: '%kernel.project_dir%/public/images/animal'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
          
