controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /
    controller: App\Controller\AccueilController::index

animal:
    path: /animal
    controller: App\Controller\AnimalController::index

habitat:
    path: /habitat
    controller: App\Controller\HabitatController::index

service:
    path: /service
    controller: App\Controller\ServiceController::index

horaire:
    path: /horaire
    controller: App\Controller\HoraireController::index

avis:
    path: /newavis
    controller: App\Controller\AvisController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index